services:
    php7:
        image: php:7.2-fpm
        user: "1000:1000"
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    php8.0:
        image: php:8.0-fpm
        user: "1000:1000"
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    php8.1:
        image: php:8.1-fpm
        working_dir: /var/www/html
        user: "1000:1000"
        volumes:
            - ./:/var/www/html

