name: CI

on:
    push:
        branches:
            - master
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 11 26 * *'

jobs:
    build-lowest-dependencies:
        name: With lowest dependencies
        runs-on: ubuntu-latest

        steps:
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.2'
                    coverage: 'none'

            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Install dependencies
                run: composer update --no-interaction --prefer-stable --prefer-lowest --no-progress --prefer-dist --ansi

            -   name: Run tests
                run: vendor/bin/simple-phpunit

    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 10
            matrix:
                php: ['7.2', '7.3', '7.4', '8.0']

        steps:
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: 'none'

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: composer update --no-interaction --prefer-stable --no-progress --prefer-dist --ansi

            -   name: Run tests
                run: vendor/bin/simple-phpunit

    build-dev-dependencies:
        name: With dev dependencies & PHP
        runs-on: ubuntu-latest

        steps:
            -   name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: 'none'

            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Allow dev dependencies
                run: composer config minimum-stability dev

            -   name: Install dependencies
                run: composer update --no-interaction --no-progress --prefer-dist --ansi

            -   name: Run tests
                continue-on-error: true
                run: vendor/bin/simple-phpunit
